USE secure_transact_db;

DELIMITER $$

-- ==========================================================
-- TRIGGER 1
-- PREVENT NEGATIVE BALANCE
-- ==========================================================

CREATE TRIGGER prevent_negative_balance

BEFORE UPDATE

ON accounts

FOR EACH ROW

BEGIN

    IF NEW.balance < 0 THEN

        SIGNAL SQLSTATE '45000'

        SET MESSAGE_TEXT = 'Account balance cannot be negative';

    END IF;

END$$



-- ==========================================================
-- TRIGGER 2
-- GENERATE ALERT FOR HIGH VALUE TRANSACTIONS
-- ==========================================================

CREATE TRIGGER high_value_transaction_alert

AFTER INSERT

ON transactions

FOR EACH ROW

BEGIN

    IF NEW.amount >= 1000000
    AND NEW.transaction_status = 'Success'
    THEN

        INSERT INTO compliance_alerts
        (
            transaction_id,
            alert_type,
            risk_level,
            alert_status,
            alert_description
        )

        VALUES
        (
            NEW.transaction_id,
            'High Value Transaction',
            'High',
            'Open',
            'Automatically generated by trigger'
        );

    END IF;

END$$



-- ==========================================================
-- TRIGGER 3
-- LOG NEW ACCOUNT CREATION
-- ==========================================================

CREATE TRIGGER account_creation_log

AFTER INSERT

ON accounts

FOR EACH ROW

BEGIN

    INSERT INTO audit_logs
    (
        employee_id,
        table_name,
        record_id,
        action_type,
        action_description,
        ip_address
    )

    VALUES
    (
        NULL,
        'accounts',
        NEW.account_id,
        'INSERT',
        CONCAT('Account Created : ',NEW.account_number),
        '127.0.0.1'
    );

END$$

DELIMITER ;